language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t stuartlogan82/docker-react -f Dockerfile.dev .

  script:
    - docker run -e CI=true stuartlogan82/docker-react npm run text -- --coverage